# Generated by Django 2.0.2 on 2019-02-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
